name: coverage

on:
  workflow_run:
    workflows: [ test ]
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: coverage
        run: echo report_coverage
