name: coverage

on:
  pull_request:
    workflow_run: [ test ]
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
  step:
    - uses: actions/checkout@v2
    - name: coverage
      run: echo report_coverage
